### ISSUE TITLE
Add option for `smooth` lines

### ISSUE THREAD

**Issue by stsdc** [dcharles525/Caroline#10]
Would be cool to have smoothed lines.
![Screen record from 2020-03-04 00 17 54](https://user-images.githubusercontent.com/6031763/75829148-bb38ab00-5dad-11ea-813e-cdfdc0b51382.gif)

**Comment by dcharles525** [comment]
@stsdc I will look into this for the next version!

**Comment by grindhold** [comment]
please make it a deactivatable feature. bezier curves are much harder to calculate and tend to decreae performance when you want to display many datapoints at once.

**Comment by dcharles525** [comment]
@grindhold Totally agree! Just a progress update on this in general I am pretty close to finally finishing this!

**Comment by dcharles525** [comment]
just merged! You can use it by specifying "smooth-line".

**Comment by grindhold** [comment]
nice
