### ISSUE TITLE
foss license

### ISSUE THREAD

**Issue by grindhold** [dcharles525/Caroline#18]
i kind of like the project and would like to contribute more but this project does not yet have a license attached. i want to make sure that code i write in my spare time will guarantee users the four freedoms. i myself use the Lesser General Public License 3 to achieve this. MIT / BSD licenses work as well. Could you please announce a license for the Project?

**Comment by dcharles525** [comment]
I added the MIT License to the repo, thanks for pointing this out and your contributions!
