### ISSUE TITLE
Add method to update data

### ISSUE THREAD

**Issue by Cogitri** [dcharles525/Caroline#19]
Hello,

first off - thanks for this library, it's really nice to use :+1: 

It'd be great if Caroline had support for reloading dataX and dataY with different values - possibly with a short animation.

**Comment by dcharles525** [comment]
@Cogitri thanks for opening these issues, I am working on this one right now, will probably be done in a few weeks along with #21. #20 I am still looking into.

**Comment by dcharles525** [comment]
Added ability to update data by using this.updateData. Check the Sample.vala file to see an example starting on line 67!
