### ISSUE TITLE
Better visualize graphs with only one datapoint in "smooth-line"

### ISSUE THREAD

**Issue by Cogitri** [dcharles525/Caroline#20]
Hello,

right now it's impossible to actually see the value of the first datapoint if there's only one datapoint (in this case it's set to 15000 for x and 0 for y):

![image](https://user-images.githubusercontent.com/8766773/94372735-88b31e80-0100-11eb-8b65-6960d03fe0e3.png)

It'd be nice if the first datapoint were a point if there's only one datapoint

**Comment by dcharles525** [comment]
Done, it now draws a point.
