### ISSUE TITLE
Allow drawing additonal line in graph, e.g. for limits

### ISSUE THREAD

**Issue by Cogitri** [dcharles525/Caroline#21]
For my usecase I want to draw a user's weight and it'd be nice if I could have a horizontal line in the graph that shows the user the weight they want to reach.

**Comment by dcharles525** [comment]
Whew, it's been a while...Working on this multi chart branch now: https://github.com/dcharles525/Caroline/tree/multichart

It still has some issues like the ~~initial load~~, documentation, and general cleanup, but if you are interested in testing it out it's there.

**Comment by dcharles525** [comment]
Done!
